apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-java
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
      - name: hello-world-java
        image: mana007.azurecr.io/hello-world:latest
        ports:
        - containerPort: 8080

# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: hello-world-java-service
spec:
  selector:
    app: hello-world-java   # Match the labels of your Deployment Pods
  ports:
    - protocol: TCP
      port: 80              # Port on the Service
      targetPort: 8080      # Port on the Pods
  type: LoadBalancer           # Type of the Service (other options: NodePort, LoadBalancer, ExternalName)
          
